spring:
  application:
    name: ecom-order-service
server:
  port: 8080

logging:
  level:
    com.hmcode.ecom_order_service.clients: DEBUG
    com.netflix.discovery: DEBUG
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 30
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    lease-renewal-interval-in-seconds: 30
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
